info:
  title: Amy Gottung
  short_bio: AMY GOTTUNG is a creative producer, consultant, researcher, and writer.
  email: amy.gottung@gmail.com
settings:
  construction_text: Check back soon.
categories:
  - Creative
  - Consulting
  - Speaking
  - Writing
