info:
  title: Amy Gottung
  short_bio: "**Amy Gottung** is a creative programmer/producer, consultant,
    researcher and writer based in Canada. She works with culture, media,
    organizations, systems, and people."
  email: amy.gottung@gmail.com
