info:
  title: Amy Gottung
  short_bio: "**Amy Gottung** is a creative producer, programmer, consultant,
    writer, and researcher. She works with culture, media, systems, and people
    around the world."
  email: amy.gottung@gmail.com
settings:
  construction_text: Check back soon.
categories:
  - Creative
  - Consulting
  - Speaking
  - Writing
